-- Create USERS table for Authentication & Authorization
CREATE TABLE USERS (
    ID VARCHAR2(50) PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) DEFAULT 'ROLE_USER' NOT NULL,
    EMAIL VARCHAR2(100),
    PHONE_NUMBER VARCHAR2(20),
    MFA_ENABLED CHAR(1) DEFAULT 'N' CHECK (MFA_ENABLED IN ('Y', 'N')),
    ACTIVE CHAR(1) DEFAULT 'Y' CHECK (ACTIVE IN ('Y', 'N')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert Initial Admin User
-- Username: admin
-- Password: admin123
-- (Hash: $2a$10$8.UnVuG9shgY3WvG/8D0ueLzVwYI9.t/y8jlyH1pWv2m.XU/y4y/S)
INSERT INTO USERS (ID, USERNAME, PASSWORD, ROLE, EMAIL, MFA_ENABLED, ACTIVE)
VALUES ('admin-id-001', 'admin', '$2a$10$8.UnVuG9shgY3WvG/8D0ueLzVwYI9.t/y8jlyH1pWv2m.XU/y4y/S', 'ROLE_ADMIN', 'admin@enterprise.com', 'N', 'Y');

COMMIT;
